### PR TITLE
ADD startInCallProximity() and stopInCallProximity()

### PR DESCRIPTION
**Pull request by fabriziomoscon**
- Allow users to control only the proximity sensor during a call

@zxcpoiu In my app I use a library which already set the audio Mode and reset it.
Using that library and this one together conflicts and reset the audio to a wrong original value.

I have added explicit calls to only use proximity, since that is the part I need and it was not exposed.

I hope if makes sense

### CODE REVIEW

**Comment by zxcpoiu** [comment]
@fabriziomoscon 

thanks for your PR.

if you already have a audio control library except proximity sensor, why not just use proximity library? such as [react-native-sensor-manager](https://github.com/pwmckenna/react-native-motion-manager)

this PR looks like a personal workaround use case, not for a general use case, said, other folks may think they are already have a proximity lib and needs to disable audio control, thus, it would may lots of customized functions in this lib.

I agree your opinion, actually, I was planning to write a newer version which can pass a `setup` object to decide which events/function/default actions should be enabled or not, but don't have enough time to do it.

if you really need to customize, it may be the way to go ( pass a setting object to decide ) and can applies to different use cases in the future.

**Comment by fabriziomoscon** [comment]
Thanks for your reply.
The library you suggested doesn't have any Android implementation. So they can't really be compared. I have actually found this library when researching for a proximity module in the first place. Please advise if you know of a library that solves that problem for Android.

I think passing a setting object is a more correct approach for the future.
In the meantime, I study all the code carefully and I saw there were other ad-hoc functions exposed, so I thought my additions were in line with the current architecture. See `startRingtone()`, `turnScreenOn()` for example.

**Comment by zxcpoiu** [comment]
ah, my bad finger, updated.
it is:  [react-native-sensor-manager](https://github.com/kprimice/react-native-sensor-manager)

**Comment by zxcpoiu** [comment]
yes, it would be better if you add a pure function for switching specific feature, like: `proximitySensor(boolean enable)`. rather than add a fat function like `start()`.

I was considering some sort of customed case, that's the reason why this module exposed some inner function to let people can do some customization if needed. these functions mostly a pure function to switching events. it's really complicated to apply different use cases.

**Comment by fabriziomoscon** [comment]
Sorry, but `react-native-sensor-manager` is a low level generic sensor access library. Has no concept of calls, which is why this library is better for my case. In fact I also need the other functions apart from proximity which are inside `startEvent()`.

Adding `proximitySensor(boolean enable)` will not fix the problem.
I think changing the underlying instance variables as flags could impact other functions, leaves room for bugs and unwanted misuse. And it makes it difficult to reason about the code.

I cannot use `stop()`, because `storeOriginalAudioSetup()` had stored a mode `AudioManager.MODE_IN_COMMUNICATION` because the other library had already set this mode.

What I really needed would be a way to prevent start from restoring the original audio, but adding flags for this would not leave us with a nice API.
The new method is copy of `startEvents()`, in fact, most probably `startInCallProximity()` is a terrible name!
But it does the trick for me.

**Comment by zxcpoiu** [comment]
thanks for mentioning different use cases, I would keep it in mind in the next version.

given that this repo not changed often, you might use your own branch for this workaround before next customizable version come.

**Comment by fabriziomoscon** [comment]
Yes, thank you. I agree. Feel free to close this

**Comment by zxcpoiu** [comment]
@fabriziomoscon

thanks, see you soon:)

**Pull request closed without merging**
