### PR TITLE
Added getIsWiredHeadsetPluggedIn to bridge methods

### PR DESCRIPTION
**Pull request by masaori**
I added native bridge method which lets me know the state of "isWiredHeadsetPluggedIn" even right after launch the app.

### CODE REVIEW

**Comment by zxcpoiu** [comment]
thanks.

here is 2 points:

1. if android is not implemented yet, add a `if Platform.OS === 'ios' .... else log not implemented yet`

2. would you mind change to promise style aligns with another functions? EX:
swift: https://github.com/zxcpoiu/react-native-incall-manager/blob/master/ios/RNInCallManager/RNInCallManager.swift#L701
js: https://github.com/zxcpoiu/react-native-incall-manager/blob/master/index.js#L145

**Comment by masaori** [comment]
Gotcha! Will do both of them.
Just a moment please.

**Comment by masaori** [comment]
@zxcpoiu 
I amended these as your instruction.
Could you check please?

**Comment by zxcpoiu** [comment]
thanks mate!

**Pull request merged**
