### PR TITLE
RN 0.4.0 support for IOS

### PR DESCRIPTION
**Pull request by jjdp**
i can't test this with an IOS version but technically this should work, right? @zxcpoiu

### CODE REVIEW

**Comment by sagivo** [comment]
@zxcpoiu we need this PR soon as we can't use this lib with react  0.40

**Comment by zxcpoiu** [comment]
Sure, thanks for testing it @sagivo 

Sorry, I'm overwhelmed recently
Will merge this 👍

**Comment by sagivo** [comment]
np, we will also need to update readme and bump version (similar to what you did in webrtc)

**Comment by zxcpoiu** [comment]
OK, I'm on my phone now,
Will do it ASAP

**Comment by sagivo** [comment]
the latest PR from @jjdp will not compile. please re-open the issue. 
there's a new PR i made - https://github.com/zxcpoiu/react-native-incall-manager/pull/24

**Pull request merged**
